### ISSUE TITLE
Calendar and Resource Tab Switch Up

### ISSUE THREAD

**Issue by GHDolphin** [LCGirlsWhoCode/LCGirlsWhoCode.github.io#6]
When you click on the Calendar page, the Calendar tab and Resource tab switch place. Also, after they switch, the three subtopics for Resource change order and become an L-shape instead of a column

**Comment by YLisao** [comment]
I'll be adding a big ol' navbar that we can link from other files… _soon_ (^～^;)ゞ but for now, we'll have to settle with copy/pasting the navbar code into the top of the <body> tag.

**This is index.html (and everywhere else):**
<img width="584" alt="Screen Shot 2020-10-29 at 4 05 30 PM" src="https://user-images.githubusercontent.com/67985867/97637586-92ca8480-1a00-11eb-9c15-33a306acbc04.png">

**And this is calendar/index.html:**
<img width="688" alt="Screen Shot 2020-10-29 at 4 06 23 PM" src="https://user-images.githubusercontent.com/67985867/97637669-b261ad00-1a00-11eb-9494-41075e76dd07.png">

They're just in the wrong place :)

I'll look into the L-shape, but it's probably an error with the CSS
